### ISSUE TITLE
祈祷数字报错

### ISSUE THREAD

**Issue by SinKy-Yan** [fluorescia/zhenxun_plugins_luckyball#1]
![@(X1LX 6@4R S3J3@SC3@M3](https://user-images.githubusercontent.com/56128013/180589701-b193c07e-86c1-4bd1-90d1-df65b40a6de1.png)

**Comment by fluoresce0** [comment]
> ![@(X1LX 6@4R S3J3@SC3@M3](https://user-images.githubusercontent.com/56128013/180589701-b193c07e-86c1-4bd1-90d1-df65b40a6de1.png)

这是因为插件名和config里对应的插件名不一致导致的。在代码里是直接获取插件名为’luckball‘下面的参数，而写入的参数的时候写在了你的’zhenxun_plugins_luckyball-main - 副本‘下面。你可以试试把插件那个文件夹名改为’luckball‘试试。或者直接进代码改get_config

**Comment by SinKy-Yan** [comment]
还是不行噢,看起来是比较的数据类型不对吧

![image](https://user-images.githubusercontent.com/56128013/180591568-be9a9555-5ab3-49b7-be1a-b38a9e5e45e6.png)

**Comment by fluoresce0** [comment]
> 还是不行噢,看起来是比较的数据类型不对吧
> 
> ![image](https://user-images.githubusercontent.com/56128013/180591568-be9a9555-5ab3-49b7-be1a-b38a9e5e45e6.png)

仍然是config名称不对应。数据类型不对是因为获取不到参数所以nonetype。为了避免这个问题，我重新改了一下代码结构，你可以将之前的插件删掉，然后装新代码试试，不过我还没测试，有无问题还麻烦回复一下，感谢。

**Comment by SinKy-Yan** [comment]
嗯,试过`祈祷数字`和开奖了,似乎没有问题了,耶!
