### ISSUE TITLE
数学上指出幸运球的问题

### ISSUE THREAD

**Issue by RShock** [fluorescia/zhenxun_plugins_luckyball#4]
先买的人第一天是用200金赌200金，期望是1/30（稳亏），这种情况会一直持续到第29次购买
买多了或者很多人买，是不亏不赚，但是前29个都是亏，导致这种平衡状态很难达到

最后谁都不愿意先买

推荐默认奖池里就有29*200金币，从而平衡期望（如果改变买入数量或者数字个数，也会对应改变初始奖池数量）

**Comment by Judp28** [comment]
确实，应该加入初始奖池，并且每次只会拿去一部分，或者有一个固定的默认奖池。
每一次中奖都掏空奖池对开始下注的人不公平。

**Comment by fluoresce0** [comment]
> 

之前有想过这个问题，但是我觉得加个基础奖池和“税收”也就一两行代码的事，想加的可以自己加。我自用的时候也是有基础奖池的，不过现在看来确实得加一加，等会儿更新一下

**Comment by fluoresce0** [comment]
> 先买的人第一天是用200金赌200金，期望是1/30（稳亏），这种情况会一直持续到第29次购买 买多了或者很多人买，是不亏不赚，但是前29个都是亏，导致这种平衡状态很难达到
> 
> 最后谁都不愿意先买
> 
> 推荐默认奖池里就有29*200金币，从而平衡期望（如果改变买入数量或者数字个数，也会对应改变初始奖池数量）

已更新

**Comment by fluoresce0** [comment]
> 先买的人第一天是用200金赌200金，期望是1/30（稳亏），这种情况会一直持续到第29次购买 买多了或者很多人买，是不亏不赚，但是前29个都是亏，导致这种平衡状态很难达到
> 
> 最后谁都不愿意先买
> 
> 推荐默认奖池里就有29*200金币，从而平衡期望（如果改变买入数量或者数字个数，也会对应改变初始奖池数量）

再稍微改了一下，按你说的，现在可以自定义基础奖池，如果不自定义则默认为购买范围*单次花费
