### ISSUE TITLE
关于开奖时间

### ISSUE THREAD

**Issue by Huang1932539** [fluorescia/zhenxun_plugins_luckyball#6]
我是一个小白，按照这个安装文档才完成真寻的布置。请问能不能通过修改文件，达成每天多次开奖呢？群友反应一天开一次太没意思了，最好能每小时或者每两小时开一次。

**Comment by fluorescia** [comment]
> 我是一个小白，按照这个安装文档才完成真寻的布置。请问能不能通过修改文件，达成每天多次开奖呢？群友反应一天开一次太没意思了，最好能每小时或者每两小时开一次。

没想到还有人在用。我提供一个方法你试试，在__init__.py的第87行（也就是“#定时任务相关”那个位置）插入以下代码试试，我不确定行不行。

@scheduler.scheduled_job(
    "interval",
    seconds=5000,#这里是每隔多少秒开奖一次
)
async def _():
    try:
        bot = get_bot()
        if bot:
                await push_calendar("这里填你的群号，字符串")
    except Exception as e:
        logger.error(f"错误:{e}")

**Comment by Huang1932539** [comment]
> > 我是一个小白，按照这个安装文档才完成真寻的布置。请问能不能通过修改文件，达成每天多次开奖呢？群友反应一天开一次太没意思了，最好能每小时或者每两小时开一次。
> 
> 没想到还有人在用。我提供一个方法你试试，在__init__.py的第87行（也就是“#定时任务相关”上面那个位置）插入以下代码试试，我不确定行不行。
> 
> ```
> @scheduler.scheduled_job(
>     "interval",
>     seconds=5000,#这里是每隔多少秒开奖一次
> )
> async def _():
>     try:
>         bot = get_bot()
>         if bot:
>                 await push_calendar("这里填你的群号，字符串")
>     except Exception as e:
>         logger.error(f"错误:{e}")
> ```

好的，我尝试一下（这个插件让我们群里整天勾心斗角（乐））

**Comment by Huang1932539** [comment]
> > 我是一个小白，按照这个安装文档才完成真寻的布置。请问能不能通过修改文件，达成每天多次开奖呢？群友反应一天开一次太没意思了，最好能每小时或者每两小时开一次。
> 
> 没想到还有人在用。我提供一个方法你试试，在__init__.py的第87行（也就是“#定时任务相关”上面那个位置）插入以下代码试试，我不确定行不行。
> 
> ```
> @scheduler.scheduled_job(
>     "interval",
>     seconds=5000,#这里是每隔多少秒开奖一次
> )
> async def _():
>     try:
>         bot = get_bot()
>         if bot:
>                 await push_calendar("这里填你的群号，字符串")
>     except Exception as e:
>         logger.error(f"错误:{e}")
> ```

不行啊，我为了测试把时间改成了600秒，结果才过了6分钟左右就开了一次，接下来直到现在都一直没开。

**Comment by fluorescia** [comment]
> 

看看报错

**Comment by fluorescia** [comment]
如果你加了真寻交流群的话直接在群里at我（fluoresce）也可以，没有就算了

**Comment by Huang1932539** [comment]
没有报错。对了，现在好了，我差不多明白刚才为什么不生效了：
我重启的时间是21:56，然后我重置时间为22:00开奖，但可能是由于文件修改，他自动从21:56开始计时，所以10分钟后也就是22:06开奖，而不是我想的22:10
总之，谢谢了。
